version: "3.7"

services:
    go-server:
        image: backend-dev
        build:
          context: .
          dockerfile: Dockerfile
        environment:
          CRED: ${USER}:${TOKEN}
        ports:
            - 8008:8008
